# Generated by Django 2.2.2 on 2019-07-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='company',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='last_email',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='preferred_contact',
        ),
    ]
