# Generated by Django 2.2.2 on 2019-07-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0002_auto_20190718_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobfinder.Companies'),
        ),
        migrations.AddField(
            model_name='applications',
            name='last_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobfinder.Job_emails'),
        ),
        migrations.AddField(
            model_name='applications',
            name='preferred_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobfinder.Company_contacts'),
        ),
    ]
